#!/usr/bin/env bash
# installs nginx and set port to 80, then serves "Hello World" on html page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
