#!/usr/bin/env bash
# Automated scripts that sets up a new server with Nginx and header

sudo apt update -y
sudo apt install nginx -y
sudo chown -R $USER:$USER /var/www/html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html

sudo sed -i "47i\ \tlocation /redirect_me {\n\t\treturn 301 \$scheme\://\$http_host\;\n\t}" /etc/nginx/sites-enabled/default

sudo sed -i "51i\ \terror_page 404 /error_404.html;\n\tlocation = /error_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n" /etc/nginx/sites-enabled/default

sudo sed -i "47i\ \n\tadd_header X-Served-By \$hostname\;\n" /etc/nginx/sites-enabled/default

sudo service nginx start

