#!/usr/bin/env bash
# dump, backup and compress my databases i
mysqldump -A -u root -p "$1" > backup.sql
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"
tar -cvfz "$file_name" backup.sql
