#!/usr/bin/env bash
# dump, backup and compress my databases i
mysqldump --all-databases -uroot -p="$1" -rbackup.sql
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"
tar -czvf "$file_name" ./backup.sql
