#!/usr/bin/env bash
#print loop of Best school at 4th prints Bad luck and at 8th iteration prints Good luck

count=1

while [ $count -le 10 ]
do
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
