#!/usr/bin/env bash
#print loop of Best school at 4th prints Bad luck and at 8th iteration prints Good luck

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	fi
	if [ $count -eq 8 ]
	then
		echo "good luck"
	fi
	
	echo "Best School"
	((count++))
done
