#!/usr/bin/bash

Let’s install the ufw firewall and setup a few rules on web-01

sudo apt install ufw -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw status
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw status verbose
yes | sudo ufw enable
sudo ufw status verbose
